version: '2.1'

services:
  simple-supply-shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: sawtooth-simple-supply-shell
    container_name: simple-supply-shell
    volumes:
      - .:/project/sawtooth-simple-supply
      - /project/sawtooth-simple-supply/curator_app/node_modules
    command: |
      bash -c "
        simple-supply-protogen
        cd curator_app/
        npm run build
        cd ../
        tail -f /dev/null
      "
  simple-supply-tp:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: sawtooth-simple-supply-tp
    container_name: simple-supply-tp
    volumes:
      - '.:/project/sawtooth-simple-supply'
    depends_on:
      - simple-supply-shell
    command: |
      bash -c "
        sleep 1
        simple-supply-tp -v -C tcp://validator:4004
      "
  simple-supply-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-simple-supply-rest-api
    container_name: simple-supply-rest-api
    volumes:
      - .:/project/sawtooth-simple-supply
    ports:
      - '8000:8000'
    depends_on:
      - simple-supply-shell
    command: |
      bash -c "
        simple-supply-rest-api \
          -B simple-supply-rest-api:8000 \
          -C validator:4004 \
          --db-host postgres \
          -vv
      "
  simple-supply-subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    image: sawtooth-simple-supply-subscriber
    container_name: simple-supply-subscriber
    volumes:
      - '.:/project/sawtooth-simple-supply'
    depends_on:
      - simple-supply-shell
      - postgres
    command: |
      bash -c "
        simple-supply-subscriber init \
          --db-host postgres \
          -vv
        sleep 3
        simple-supply-subscriber subscribe \
          --db-host postgres \
          -C tcp://validator:4004 \
          -vv
      "
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004
  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008
  validator:
    image: hyperledger/sawtooth-validator:1.2
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: ${CMD}
  postgres:
    image: postgres:alpine
    container_name: simple-supply-postgres
    restart: always
    environment:
      POSTGRES_USER: sawtooth
      POSTGRES_PASSWORD: sawtooth
      POSTGRES_DB: simple-supply
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    container_name: simple-supply-adminer
    restart: always
    ports:
      - '8090:8090'
  curator-app:
    build: ./curator_app
    image: simple-supply-curator-app
    container_name: curator-app
    volumes:
      - ./curator_app/public/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8040:80'
    depends_on:
      - simple-supply-shell
      - simple-supply-rest-api 

