# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: '2.2'
volumes:
  pbft-shared:
services:
# -------------=== intkey tp ===-------------
  intkey-tp-0:
    image: hyperledger/sawtooth-intkey-tp-go:latest
    container_name: sawtooth-intkey-tp-go-default-0
    expose:
      - 4004
    command: intkey-tp-go -C tcp://validator-0:4004
    stop_signal: SIGKILL
  intkey-tp-1:
    image: hyperledger/sawtooth-intkey-tp-go:latest
    container_name: sawtooth-intkey-tp-go-default-1
    expose:
      - 4004
    command: intkey-tp-go -C tcp://validator-1:4004
    stop_signal: SIGKILL
  intkey-tp-2:
    image: hyperledger/sawtooth-intkey-tp-go:latest
    container_name: sawtooth-intkey-tp-go-default-2
    expose:
      - 4004
    command: intkey-tp-go -C tcp://validator-2:4004
    stop_signal: SIGKILL
  intkey-tp-3:
    image: hyperledger/sawtooth-intkey-tp-go:latest
    container_name: sawtooth-intkey-tp-go-default-3
    expose:
      - 4004
    command: intkey-tp-go -C tcp://validator-3:4004
    stop_signal: SIGKILL
  intkey-tp-4:
    image: hyperledger/sawtooth-intkey-tp-go:latest
    container_name: sawtooth-intkey-tp-go-default-4
    expose:
      - 4004
    command: intkey-tp-go -C tcp://validator-4:4004
    stop_signal: SIGKILL
# -------------=== rest api ===-------------
  rest-api-0:
    image: hyperledger/sawtooth-rest-api:1.2.4
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8008
    ports:
      - 8008:8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL
  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.2.4
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL
  rest-api-2:
    image: hyperledger/sawtooth-rest-api:1.2.4
    container_name: sawtooth-rest-api-default-2
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-2:4004 \
          --bind rest-api-2:8008
      "
    stop_signal: SIGKILL
  rest-api-3:
    image: hyperledger/sawtooth-rest-api:1.2.4
    container_name: sawtooth-rest-api-default-3
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-3:4004 \
          --bind rest-api-3:8008
      "
    stop_signal: SIGKILL
  rest-api-4:
    image: hyperledger/sawtooth-rest-api:1.2.4
    container_name: sawtooth-rest-api-default-4
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-4:4004 \
          --bind rest-api-4:8008
      "
    stop_signal: SIGKILL
# -------------=== settings tp ===-------------
  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:1.2.4
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL
  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.2.4
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL
  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:1.2.4
    container_name: sawtooth-settings-tp-default-2
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL
  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:1.2.4
    container_name: sawtooth-settings-tp-default-3
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL
  settings-tp-4:
    image: hyperledger/sawtooth-settings-tp:1.2.4
    container_name: sawtooth-settings-tp-default-4
    expose:
      - 4004
    command: settings-tp -C tcp://validator-4:4004
    stop_signal: SIGKILL
# -------------=== shell ===-------------
  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL
# -------------=== validators ===-------------
  # validator-0:
  #   image: hyperledger/sawtooth-validator:chime
  #   container_name: sawtooth-validator-default-0
  #   expose:
  #     - 4004
  #     - 5050
  #     - 8800
  #   ports:
  #     - 4004:4004
  #   volumes:
  #     - pbft-shared:/pbft-shared
  #     - .:/pbft
  #   command: |
  #     bash -c "
  #       /pbft/first_run_genesis.sh &&
  #       sawtooth-validator -vv \
  #         --endpoint tcp://validator-0:8800 \
  #         --bind component:tcp://eth0:4004 \
  #         --bind consensus:tcp://eth0:5050 \
  #         --bind network:tcp://eth0:8800 \
  #         --scheduler parallel \
  #         --peering static \
  #         --maximum-peer-connectivity 10000
  #     "

  validator-0:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator
    expose:
        - 4004
        - 5050
        - 8800
    ports:
        - '4004:4004'
    volumes:
        - pbft-shared:/pbft-shared
    command: |
        bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen
        sawtooth keygen my_key
        sawset genesis -k /root/.sawtooth/keys/my_key.priv
        sawset proposal create -k /root/.sawtooth/keys/my_key.priv \
            sawtooth.consensus.algorithm.name=Devmode \
            sawtooth.consensus.algorithm.version=0.1 \
            -o config.batch
        sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vv \
        --endpoint tcp://validator-0:8800 \
        --bind component:tcp://eth0:4004 \
        --bind network:tcp://eth0:8800 \
        --bind consensus:tcp://eth0:5050 \
        --scheduler parallel \
        --peering static \
        --maximum-peer-connectivity 10000"
  validator-1:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-1
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
      - .:/pbft
    command: |
      bash -c "
      /pbft/first_run.sh 1 &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800
      "
  validator-2:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-2
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
      - .:/pbft
    command: |
      bash -c "
      /pbft/first_run.sh 2 &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-2:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800
      "
  validator-3:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-3
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
      - .:/pbft
    command: |
      bash -c "
      /pbft/first_run.sh 3 &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-3:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800
      "
  validator-4:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-4
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
      - .:/pbft
    command: |
      bash -c "
      /pbft/first_run.sh 4 &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-4:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800
      "
# -------------=== pbft engines ===-------------
  pbft-0:
    image: hyperledger/sawtooth-pbft-engine:1.0.2
    container_name: sawtooth-pbft-engine-default-0
    command: pbft-engine -vv --connect tcp://validator-0:5050
    stop_signal: SIGKILL
  pbft-1:
    image: hyperledger/sawtooth-pbft-engine:1.0.2
    container_name: sawtooth-pbft-engine-default-1
    command: pbft-engine -vv --connect tcp://validator-1:5050
    stop_signal: SIGKILL
  pbft-2:
    image: hyperledger/sawtooth-pbft-engine:1.0.2
    container_name: sawtooth-pbft-engine-default-2
    command: pbft-engine -vv --connect tcp://validator-2:5050
    stop_signal: SIGKILL
  pbft-3:
    image: hyperledger/sawtooth-pbft-engine:1.0.2
    container_name: sawtooth-pbft-engine-default-3
    command: pbft-engine -vv --connect tcp://validator-3:5050
    stop_signal: SIGKILL
  pbft-4:
    image: hyperledger/sawtooth-pbft-engine:1.0.2
    container_name: sawtooth-pbft-engine-default-4
    command: pbft-engine -vv --connect tcp://validator-4:5050
    stop_signal: SIGKILL
